export const imgUrl = {
  row1: {
    img1:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Projects/HelpPage/BubbleShoveler/English/Fuji_Bubble_8Languages_en_US_updated_1x._CB445837675_.png",
    img2:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_Currency_en_US_1X._CB451228332_.jpg",
    img3:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_SecurePayment_en_US_1X._CB451228335_.jpg",
    img4:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_ImportFees_en_US_1X._CB451228332_.jpg",
    img5:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_TrackPackage_en_US_1X._CB451228335_.jpg",
    img6:
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_247CS_en_US_1X._CB451228332_.jpg",
  },
  row2: {
    img1: "https://m.media-amazon.com/images/I/11tEFlSGn6L._AC_SY200_.jpg",
    img2: "https://m.media-amazon.com/images/I/41ffko0T3kL._AC_SY200_.jpg",
    img3: "https://m.media-amazon.com/images/I/41KL+iXUXCL._AC_SY200_.jpg",
    img4: "https://m.media-amazon.com/images/I/51G8LfsNZzL._AC_SY200_.jpg",
    img5: "https://m.media-amazon.com/images/I/31i3tpuXxxL._AC_SY200_.jpg",
    img6: "https://m.media-amazon.com/images/I/41yavwjp-8L._AC_SY200_.jpg",
    img7: "https://m.media-amazon.com/images/I/41i+z-JR+zL._AC_SY200_.jpg",
    img8: "https://m.media-amazon.com/images/I/41W5-duvLkL._AC_SY200_.jpg",
    img9: "https://m.media-amazon.com/images/I/41g0C69FbvL._AC_SY200_.jpg",
    img10: "https://m.media-amazon.com/images/I/41tQ9dniedL._AC_SY200_.jpg",
    img11: "https://m.media-amazon.com/images/I/41bCxnHksnL._AC_SY200_.jpg",
    img12: "https://m.media-amazon.com/images/I/41GGPRqTZtL._AC_SY200_.jpg",
    img13: "https://m.media-amazon.com/images/I/51-0Dt6WeSL._AC_SY200_.jpg",
    img14: "https://m.media-amazon.com/images/I/416IxcmUpGL._AC_SY200_.jpg",
    img15: "https://m.media-amazon.com/images/I/51C17DrwacL._AC_SY200_.jpg",
    img16: "https://m.media-amazon.com/images/I/41LO2OX6pRL._AC_SY200_.jpg",
    img17: "https://m.media-amazon.com/images/I/41cEMMExIoL._AC_SY200_.jpg",
    img18: "https://m.media-amazon.com/images/I/51EFHtOLKxL._AC_SY200_.jpg",
    img19: "https://m.media-amazon.com/images/I/31qwualUaLL._AC_SY200_.jpg",
    img20: "https://m.media-amazon.com/images/I/315t-VOAjgL._AC_SY200_.jpg",
  },
  row3: {
    img1: "https://m.media-amazon.com/images/I/41IF4qzFnEL._AC_SY200_.jpg",
    img2: "https://m.media-amazon.com/images/I/41TWHhFUC3L._AC_SY200_.jpg",
    img3: "https://m.media-amazon.com/images/I/41AZOLr72bL._AC_SY200_.jpg",
    img4: "https://m.media-amazon.com/images/I/313I+J9L3jL._AC_SY200_.jpg",
    img5: "https://m.media-amazon.com/images/I/51PxpmVf51L._AC_SY200_.jpg",
    img6: "https://m.media-amazon.com/images/I/41zr88j+byL._AC_SY200_.jpg",
    img7: "https://m.media-amazon.com/images/I/41hyN1iiHfL._AC_SY200_.jpg",
    img8: "https://m.media-amazon.com/images/I/41N8AxIJq4L._AC_SY200_.jpg",
    img9: "https://m.media-amazon.com/images/I/51XFpX+XFpL._AC_SY200_.jpg",
    img10: "https://m.media-amazon.com/images/I/41NPVXxKO3L._AC_SY200_.jpg",
    img11: "https://m.media-amazon.com/images/I/41Kf0mndKyL._AC_SY200_.jpg",
    img12: "https://m.media-amazon.com/images/I/41M7H27d+hL._AC_SY200_.jpg",
    img13: "https://m.media-amazon.com/images/I/419mxWvwrcL._AC_SY200_.jpg",
    img14: "https://m.media-amazon.com/images/I/41MUBAPIW7L._AC_SY200_.jpg",
    img15: "https://m.media-amazon.com/images/I/41fgkBDrkxL._AC_SY200_.jpg",
    img16: "https://m.media-amazon.com/images/I/31jy5fSzyRL._AC_SY200_.jpg",
    img17: "https://m.media-amazon.com/images/I/31FZDSUNb3L._AC_SY200_.jpg",
    img18: "https://m.media-amazon.com/images/I/41zR9OmibVL._AC_SY200_.jpg",
    img19: "",
    img20: "",
  },
  row4: {
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
    img11: "",
    img12: "",
    img13: "",
    img14: "",
    img15: "",
    img16: "",
    img17: "",
    img18: "",
    img19: "",
    img20: "",
  },
};
